import { test, expect } from '@playwright/test';
test('api-call_5_0', async({page,context})=>{ const status=200; expect(status).toBe(200); });
test('screenshot-capture_5_1', async({page,context})=>{ await page.goto('https://example.com'); await page.screenshot({path:'snap.png'}); });
test('file-upload_5_2', async({page,context})=>{ await page.goto('https://www.w3schools.com/howto/howto_html_file_upload_button.asp'); await page.setInputFiles('input[type=file]','fixtures/sample-upload.txt'); });
test('flaky_5_3', async({page,context})=>{ if(Math.random()>0.5) expect(1).toBe(1); else expect(1).toBe(2); });
test('slow_5_4', async({page,context})=>{ await new Promise(r=>setTimeout(r,3000)); });
test('timeout_5_5', async({page,context})=>{ await new Promise(r=>setTimeout(r,60000)); });
test('pass_5_6', async({page,context})=>{ await expect(1).toBe(1); });
test('pass_5_7', async({page,context})=>{ await expect(1).toBe(1); });
test.skip('skip_5_8', async()=>{});
test('ui-wait_5_9', async({page,context})=>{ await page.waitForTimeout(2000); });
test('fail_5_10', async({page,context})=>{ await expect(1).toBe(2); });
test('slow_5_11', async({page,context})=>{ await new Promise(r=>setTimeout(r,3000)); });
test('popup-handling_5_12', async({page,context})=>{ page.once('dialog',d=>d.dismiss()); await page.evaluate(()=>alert('x')); });
test.skip('skip_5_13', async()=>{});
test('multiple-tabs_5_14', async({page,context})=>{ const p2=await context.newPage(); await page.goto('https://example.com'); await p2.goto('https://playwright.dev'); });
test('api-call_5_15', async({page,context})=>{ const status=200; expect(status).toBe(200); });
test('random-error_5_16', async({page,context})=>{ if(Math.random()>0.7) throw new Error('Random crash'); });
test('random-error_5_17', async({page,context})=>{ if(Math.random()>0.7) throw new Error('Random crash'); });
test('browser-navigation_5_18', async({page,context})=>{ await page.goto('https://example.com'); });
test.skip('skip_5_19', async()=>{});
