import { test, expect } from '@playwright/test';
test('screenshot-capture_4_0', async({page,context})=>{ await page.goto('https://example.com'); await page.screenshot({path:'snap.png'}); });
test('pass_4_1', async({page,context})=>{ await expect(1).toBe(1); });
test('api-call_4_2', async({page,context})=>{ const status=200; expect(status).toBe(200); });
test('multiple-tabs_4_3', async({page,context})=>{ const p2=await context.newPage(); await page.goto('https://example.com'); await p2.goto('https://playwright.dev'); });
test.skip('skip_4_4', async()=>{});
test('popup-handling_4_5', async({page,context})=>{ page.once('dialog',d=>d.dismiss()); await page.evaluate(()=>alert('x')); });
test('random-error_4_6', async({page,context})=>{ if(Math.random()>0.7) throw new Error('Random crash'); });
test('file-upload_4_7', async({page,context})=>{ await page.goto('https://www.w3schools.com/howto/howto_html_file_upload_button.asp'); await page.setInputFiles('input[type=file]','fixtures/sample-upload.txt'); });
test('ui-wait_4_8', async({page,context})=>{ await page.waitForTimeout(2000); });
test('random-error_4_9', async({page,context})=>{ if(Math.random()>0.7) throw new Error('Random crash'); });
test('api-call_4_10', async({page,context})=>{ const status=200; expect(status).toBe(200); });
test('flaky_4_11', async({page,context})=>{ if(Math.random()>0.5) expect(1).toBe(1); else expect(1).toBe(2); });
test('multiple-tabs_4_12', async({page,context})=>{ const p2=await context.newPage(); await page.goto('https://example.com'); await p2.goto('https://playwright.dev'); });
test('pass_4_13', async({page,context})=>{ await expect(1).toBe(1); });
test('file-upload_4_14', async({page,context})=>{ await page.goto('https://www.w3schools.com/howto/howto_html_file_upload_button.asp'); await page.setInputFiles('input[type=file]','fixtures/sample-upload.txt'); });
test('screenshot-capture_4_15', async({page,context})=>{ await page.goto('https://example.com'); await page.screenshot({path:'snap.png'}); });
test('element-not-found_4_16', async({page,context})=>{ await page.waitForSelector('#missing',{timeout:3000}); });
test('slow_4_17', async({page,context})=>{ await new Promise(r=>setTimeout(r,3000)); });
test('multiple-tabs_4_18', async({page,context})=>{ const p2=await context.newPage(); await page.goto('https://example.com'); await p2.goto('https://playwright.dev'); });
test.skip('skip_4_19', async()=>{});
