const { test, expect } = require('@playwright/test');
test.skip('skip_2_0', async()=>{});
test('element-not-found_2_1', async({page,context})=>{ await page.waitForSelector('#missing',{timeout:3000}); });
test('screenshot-capture_2_2', async({page,context})=>{ await page.goto('https://example.com'); await page.screenshot({path:'snap.png'}); });
test('screenshot-capture_2_3', async({page,context})=>{ await page.goto('https://example.com'); await page.screenshot({path:'snap.png'}); });
test('fail_2_4', async({page,context})=>{ await expect(1).toBe(2); });
test.skip('skip_2_5', async()=>{});
test('ui-wait_2_6', async({page,context})=>{ await page.waitForTimeout(2000); });
test('screenshot-capture_2_7', async({page,context})=>{ await page.goto('https://example.com'); await page.screenshot({path:'snap.png'}); });
test('ui-wait_2_8', async({page,context})=>{ await page.waitForTimeout(2000); });
test('flaky_2_9', async({page,context})=>{ if(Math.random()>0.5) expect(1).toBe(1); else expect(1).toBe(2); });
test('storage-read-write_2_10', async({page,context})=>{ await page.goto('https://example.com'); await page.evaluate(()=>localStorage.setItem('k','v')); });
test('file-upload_2_11', async({page,context})=>{ await page.goto('https://www.w3schools.com/howto/howto_html_file_upload_button.asp'); await page.setInputFiles('input[type=file]','fixtures/sample-upload.txt'); });
test('slow_2_12', async({page,context})=>{ await new Promise(r=>setTimeout(r,3000)); });
test('storage-read-write_2_13', async({page,context})=>{ await page.goto('https://example.com'); await page.evaluate(()=>localStorage.setItem('k','v')); });
test('random-error_2_14', async({page,context})=>{ if(Math.random()>0.7) throw new Error('Random crash'); });
test('api-call_2_15', async({page,context})=>{ const status=200; expect(status).toBe(200); });
test('pass_2_16', async({page,context})=>{ await expect(1).toBe(1); });
test('random-error_2_17', async({page,context})=>{ if(Math.random()>0.7) throw new Error('Random crash'); });
test('flaky_2_18', async({page,context})=>{ if(Math.random()>0.5) expect(1).toBe(1); else expect(1).toBe(2); });
test('screenshot-capture_2_19', async({page,context})=>{ await page.goto('https://example.com'); await page.screenshot({path:'snap.png'}); });
