const { test, expect } = require('@playwright/test');
test('slow_8_0', async({page,context})=>{ await new Promise(r=>setTimeout(r,3000)); });
test('multiple-tabs_8_1', async({page,context})=>{ const p2=await context.newPage(); await page.goto('https://example.com'); await p2.goto('https://playwright.dev'); });
test('file-upload_8_2', async({page,context})=>{ await page.goto('https://www.w3schools.com/howto/howto_html_file_upload_button.asp'); await page.setInputFiles('input[type=file]','fixtures/sample-upload.txt'); });
test('pass_8_3', async({page,context})=>{ await expect(1).toBe(1); });
test('screenshot-capture_8_4', async({page,context})=>{ await page.goto('https://example.com'); await page.screenshot({path:'snap.png'}); });
test('element-not-found_8_5', async({page,context})=>{ await page.waitForSelector('#missing',{timeout:3000}); });
test('popup-handling_8_6', async({page,context})=>{ page.once('dialog',d=>d.dismiss()); await page.evaluate(()=>alert('x')); });
test('file-upload_8_7', async({page,context})=>{ await page.goto('https://www.w3schools.com/howto/howto_html_file_upload_button.asp'); await page.setInputFiles('input[type=file]','fixtures/sample-upload.txt'); });
test('file-upload_8_8', async({page,context})=>{ await page.goto('https://www.w3schools.com/howto/howto_html_file_upload_button.asp'); await page.setInputFiles('input[type=file]','fixtures/sample-upload.txt'); });
test('popup-handling_8_9', async({page,context})=>{ page.once('dialog',d=>d.dismiss()); await page.evaluate(()=>alert('x')); });
test('pass_8_10', async({page,context})=>{ await expect(1).toBe(1); });
test('ui-wait_8_11', async({page,context})=>{ await page.waitForTimeout(2000); });
test('api-call_8_12', async({page,context})=>{ const status=200; expect(status).toBe(200); });
test('screenshot-capture_8_13', async({page,context})=>{ await page.goto('https://example.com'); await page.screenshot({path:'snap.png'}); });
test('screenshot-capture_8_14', async({page,context})=>{ await page.goto('https://example.com'); await page.screenshot({path:'snap.png'}); });
test('popup-handling_8_15', async({page,context})=>{ page.once('dialog',d=>d.dismiss()); await page.evaluate(()=>alert('x')); });
test('api-call_8_16', async({page,context})=>{ const status=200; expect(status).toBe(200); });
test('flaky_8_17', async({page,context})=>{ if(Math.random()>0.5) expect(1).toBe(1); else expect(1).toBe(2); });
test('fail_8_18', async({page,context})=>{ await expect(1).toBe(2); });
test('element-not-found_8_19', async({page,context})=>{ await page.waitForSelector('#missing',{timeout:3000}); });
